### ISSUE TITLE
Фатальная ошибка в тесте (вылет программы)

### ISSUE THREAD

**Issue by DeKinci** [Kotlin-Polytech/KotlinAsFirst2017#1]
В третьем уроке, в функции squareBetweenExists вылетает AssertionFailedError на последнем тесте 
assertFalse(squareBetweenExists(2147395601, Int.MAX_VALUE))

**Comment by belyaev-mikhail** [comment]
И в чем же, по вашему, заключается ошибка?

Между `2147395601` и `Int.MAX_VALUE` (`2147483647`) полных квадратов действительно нет.
Ближайшие квадраты это `2147395600 = 46340 * 46340` и `2147488281 = 46341 * 46341`, тест корректен.

**Comment by DeKinci** [comment]
Извиняюсь, был не прав
