### ISSUE TITLE
Перепутаны местами функции

### ISSUE THREAD

**Issue by DeKinci** [Kotlin-Polytech/KotlinAsFirst2017#2]
Во уроке 2 таске 2 перепутаны местами две последние функции относительно функций в тестах
Задание:           Тесты:
circleInside        brickPasses
brickPasses        circleInside        

Не критично, но фрустрирует

**Comment by belyaev-mikhail** [comment]
Функции местами перепутаны действительно, мы это учтём на будущее.
В следующих уроках скорее всего расхождения в порядке тоже есть.

Однако, на данный момент мы пытаемся как можно сильнее избегать правок базового репозитория, потому что такие правки заставляют **всех** студентов нетривиально сливать с ними свои изменения, что увеличивает головной боли всем участникам процесса на порядок.

Можете открыть тикет к [вот этому репозиторию](https://github.com/Kotlin-Polytech/KotlinAsFirst), но репозиторий 2017 года останется на этой ревизии настолько долго, насколько в нём нет совсем критических ошибок. Если таковые ошибки найдутся, может быть, заодно мы и тесты местами переставим.
