### ISSUE TITLE
Ошибка тестов в третьем уроке, задании sin

### ISSUE THREAD

**Issue by DeKinci** [Kotlin-Polytech/KotlinAsFirst2017#3]
В том случае, если расхождение ожидаемого и реального значения имеется, 
но указанная точность СОБЛЮДЕНА, котоед считает решение неправильным.
Пример (из рандомного теста котоеда): 
assertEquals(0.9743700647496503, sin(-17.051866791984597, 1e-10))

expected: <0.9743700647496503> 
but   was: <0.9743700647857987>

Как можно заметить, разница меньше 1е-10 (а именно 3.6148418e-11)

В задании же указано, что достаточно вычислить sin(x) с указанной точностью, то есть предложенный ответ следует считать верным

**Comment by belyaev-mikhail** [comment]
У вас в решении падает ваш собственный некорректный тест, который вы сами туда добавили.
У него вообще не задана точность, поэтому работать он не может, но это вы его таким написали.
Все случайные тесты на данный момент проходят.

Посему ваша претензия мне непонятна от слова "совсем".

**Comment by DeKinci** [comment]
Эхх, простите, опять
Никак не могу научиться терпению...
Что самое забавное, я даже не знаю, откуда этот тест взялся

**Comment by belyaev-mikhail** [comment]
Судя по всему, он взялся вот отсюда http://kotoed.icc.spbstu.ru:9000/views/submission/215/results.

Вы добавили тест, забыв, что `Double` нельзя сравнивать на равенство (там специально для этого в ассертах указывается точность), а потом забыли, что сами же его добавили.
